/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiBarbsRouteImport } from './routes/api/barbs'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedAppSettingsRouteImport } from './routes/_authenticated/app.settings'
import { Route as AuthenticatedAppSentimentRouteImport } from './routes/_authenticated/app.sentiment'
import { Route as AuthenticatedAppPcrRouteImport } from './routes/_authenticated/app.pcr'
import { Route as AuthenticatedAppDashboardRouteImport } from './routes/_authenticated/app.dashboard'
import { Route as AuthenticatedAppCreativeRouteImport } from './routes/_authenticated/app.creative'
import { Route as AuthenticatedAppBenchmarksRouteImport } from './routes/_authenticated/app.benchmarks'
import { Route as AuthenticatedAppAdvisorRouteImport } from './routes/_authenticated/app.advisor'
import { Route as AuthenticatedAppAdvertisersRouteImport } from './routes/_authenticated/app.advertisers'
import { Route as ApiPublicHooksScanReadyRouteImport } from './routes/api/public/hooks/scan-ready'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBarbsRoute = ApiBarbsRouteImport.update({
  id: '/api/barbs',
  path: '/api/barbs',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppSettingsRoute =
  AuthenticatedAppSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppSentimentRoute =
  AuthenticatedAppSentimentRouteImport.update({
    id: '/sentiment',
    path: '/sentiment',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppPcrRoute = AuthenticatedAppPcrRouteImport.update({
  id: '/pcr',
  path: '/pcr',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppDashboardRoute =
  AuthenticatedAppDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppCreativeRoute =
  AuthenticatedAppCreativeRouteImport.update({
    id: '/creative',
    path: '/creative',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppBenchmarksRoute =
  AuthenticatedAppBenchmarksRouteImport.update({
    id: '/benchmarks',
    path: '/benchmarks',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppAdvisorRoute = AuthenticatedAppAdvisorRouteImport.update({
  id: '/advisor',
  path: '/advisor',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppAdvertisersRoute =
  AuthenticatedAppAdvertisersRouteImport.update({
    id: '/advertisers',
    path: '/advertisers',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const ApiPublicHooksScanReadyRoute = ApiPublicHooksScanReadyRouteImport.update({
  id: '/api/public/hooks/scan-ready',
  path: '/api/public/hooks/scan-ready',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/api/barbs': typeof ApiBarbsRoute
  '/app/advertisers': typeof AuthenticatedAppAdvertisersRoute
  '/app/advisor': typeof AuthenticatedAppAdvisorRoute
  '/app/benchmarks': typeof AuthenticatedAppBenchmarksRoute
  '/app/creative': typeof AuthenticatedAppCreativeRoute
  '/app/dashboard': typeof AuthenticatedAppDashboardRoute
  '/app/pcr': typeof AuthenticatedAppPcrRoute
  '/app/sentiment': typeof AuthenticatedAppSentimentRoute
  '/app/settings': typeof AuthenticatedAppSettingsRoute
  '/api/public/hooks/scan-ready': typeof ApiPublicHooksScanReadyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/api/barbs': typeof ApiBarbsRoute
  '/app/advertisers': typeof AuthenticatedAppAdvertisersRoute
  '/app/advisor': typeof AuthenticatedAppAdvisorRoute
  '/app/benchmarks': typeof AuthenticatedAppBenchmarksRoute
  '/app/creative': typeof AuthenticatedAppCreativeRoute
  '/app/dashboard': typeof AuthenticatedAppDashboardRoute
  '/app/pcr': typeof AuthenticatedAppPcrRoute
  '/app/sentiment': typeof AuthenticatedAppSentimentRoute
  '/app/settings': typeof AuthenticatedAppSettingsRoute
  '/api/public/hooks/scan-ready': typeof ApiPublicHooksScanReadyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/app': typeof AuthenticatedAppRouteWithChildren
  '/api/barbs': typeof ApiBarbsRoute
  '/_authenticated/app/advertisers': typeof AuthenticatedAppAdvertisersRoute
  '/_authenticated/app/advisor': typeof AuthenticatedAppAdvisorRoute
  '/_authenticated/app/benchmarks': typeof AuthenticatedAppBenchmarksRoute
  '/_authenticated/app/creative': typeof AuthenticatedAppCreativeRoute
  '/_authenticated/app/dashboard': typeof AuthenticatedAppDashboardRoute
  '/_authenticated/app/pcr': typeof AuthenticatedAppPcrRoute
  '/_authenticated/app/sentiment': typeof AuthenticatedAppSentimentRoute
  '/_authenticated/app/settings': typeof AuthenticatedAppSettingsRoute
  '/api/public/hooks/scan-ready': typeof ApiPublicHooksScanReadyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/forgot-password'
    | '/reset-password'
    | '/app'
    | '/api/barbs'
    | '/app/advertisers'
    | '/app/advisor'
    | '/app/benchmarks'
    | '/app/creative'
    | '/app/dashboard'
    | '/app/pcr'
    | '/app/sentiment'
    | '/app/settings'
    | '/api/public/hooks/scan-ready'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/forgot-password'
    | '/reset-password'
    | '/app'
    | '/api/barbs'
    | '/app/advertisers'
    | '/app/advisor'
    | '/app/benchmarks'
    | '/app/creative'
    | '/app/dashboard'
    | '/app/pcr'
    | '/app/sentiment'
    | '/app/settings'
    | '/api/public/hooks/scan-ready'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/forgot-password'
    | '/reset-password'
    | '/_authenticated/app'
    | '/api/barbs'
    | '/_authenticated/app/advertisers'
    | '/_authenticated/app/advisor'
    | '/_authenticated/app/benchmarks'
    | '/_authenticated/app/creative'
    | '/_authenticated/app/dashboard'
    | '/_authenticated/app/pcr'
    | '/_authenticated/app/sentiment'
    | '/_authenticated/app/settings'
    | '/api/public/hooks/scan-ready'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ApiBarbsRoute: typeof ApiBarbsRoute
  ApiPublicHooksScanReadyRoute: typeof ApiPublicHooksScanReadyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/barbs': {
      id: '/api/barbs'
      path: '/api/barbs'
      fullPath: '/api/barbs'
      preLoaderRoute: typeof ApiBarbsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/settings': {
      id: '/_authenticated/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AuthenticatedAppSettingsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/sentiment': {
      id: '/_authenticated/app/sentiment'
      path: '/sentiment'
      fullPath: '/app/sentiment'
      preLoaderRoute: typeof AuthenticatedAppSentimentRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/pcr': {
      id: '/_authenticated/app/pcr'
      path: '/pcr'
      fullPath: '/app/pcr'
      preLoaderRoute: typeof AuthenticatedAppPcrRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/dashboard': {
      id: '/_authenticated/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AuthenticatedAppDashboardRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/creative': {
      id: '/_authenticated/app/creative'
      path: '/creative'
      fullPath: '/app/creative'
      preLoaderRoute: typeof AuthenticatedAppCreativeRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/benchmarks': {
      id: '/_authenticated/app/benchmarks'
      path: '/benchmarks'
      fullPath: '/app/benchmarks'
      preLoaderRoute: typeof AuthenticatedAppBenchmarksRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/advisor': {
      id: '/_authenticated/app/advisor'
      path: '/advisor'
      fullPath: '/app/advisor'
      preLoaderRoute: typeof AuthenticatedAppAdvisorRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/advertisers': {
      id: '/_authenticated/app/advertisers'
      path: '/advertisers'
      fullPath: '/app/advertisers'
      preLoaderRoute: typeof AuthenticatedAppAdvertisersRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/api/public/hooks/scan-ready': {
      id: '/api/public/hooks/scan-ready'
      path: '/api/public/hooks/scan-ready'
      fullPath: '/api/public/hooks/scan-ready'
      preLoaderRoute: typeof ApiPublicHooksScanReadyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppAdvertisersRoute: typeof AuthenticatedAppAdvertisersRoute
  AuthenticatedAppAdvisorRoute: typeof AuthenticatedAppAdvisorRoute
  AuthenticatedAppBenchmarksRoute: typeof AuthenticatedAppBenchmarksRoute
  AuthenticatedAppCreativeRoute: typeof AuthenticatedAppCreativeRoute
  AuthenticatedAppDashboardRoute: typeof AuthenticatedAppDashboardRoute
  AuthenticatedAppPcrRoute: typeof AuthenticatedAppPcrRoute
  AuthenticatedAppSentimentRoute: typeof AuthenticatedAppSentimentRoute
  AuthenticatedAppSettingsRoute: typeof AuthenticatedAppSettingsRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppAdvertisersRoute: AuthenticatedAppAdvertisersRoute,
  AuthenticatedAppAdvisorRoute: AuthenticatedAppAdvisorRoute,
  AuthenticatedAppBenchmarksRoute: AuthenticatedAppBenchmarksRoute,
  AuthenticatedAppCreativeRoute: AuthenticatedAppCreativeRoute,
  AuthenticatedAppDashboardRoute: AuthenticatedAppDashboardRoute,
  AuthenticatedAppPcrRoute: AuthenticatedAppPcrRoute,
  AuthenticatedAppSentimentRoute: AuthenticatedAppSentimentRoute,
  AuthenticatedAppSettingsRoute: AuthenticatedAppSettingsRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ApiBarbsRoute: ApiBarbsRoute,
  ApiPublicHooksScanReadyRoute: ApiPublicHooksScanReadyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
